config/routes.rb
Rails.application.routes.draw do

  resources :users, shallow: true do
    member do
      resources :galleries do
        member do
          resources :photos
        end
      end
    end
  end

  root 'users#marketing'

  get "/login" => 'sessions#new', as: :login
  post "/login" => 'sessions#create'
  delete "/logout" => 'sessions#destroy', as: :logout
  # get "//galleries/:gallery_id/photos/:id"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
  has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord

  has_one :user,  through: :galleries

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord

  has_many :galleries
  has_many :photos, through: :galleries
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless current_user
      flash[:warning] = "You should log in before you do that."
      redirect_to login_path
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new(params[:user_id])
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def create
    @gallery = current_user.galleries.new(gallery_params)
    if @gallery.save
      redirect_to @gallery
    else
      render :new
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:title)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @photo = Photo.new(params[:user_id])
  end

  def create
    @photo = current_user.photos.new(photo_params)
    current_gallery = Gallery.find(params[:id])
    if current_gallery.user == current_user
      current_gallery.photos << @photo
      current_gallery.save
      redirect_to current_gallery
    else
      render :new
    end
  end

  def index
    @photos = Photo.all
  end

  def show
    @photos = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :id, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        flash[:success] = "Hey there, #{@user.username}"
        redirect_to @user
      else
        flash[:danger] = "You entered the wrong username and/or password.  Please try again."
        redirect_to login_path
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  def new
    @user =  User.new
  end

  def create
    @user = User.new(user_params)
    if
      @user.save
      # send them an email
      UserMailer.signup(@user).deliver
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end



  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/index.html.erb
<h4>This page is in memory of the late David from The Iron Yard</h4>
<button type="button" class="btn btn-success">Share Gallery</button>
<button type="button" class="btn btn-danger">Delete Gallery</button>
 <%= link_to "Make New Gallery", new_gallery_path(@user), class: "btn btn-default" %>

<div class="media">
  <div class="media-left">
    <% @galleries.each do |gallery| %>
      <%= simple_format gallery.title %>
      <strong>Posted by <%= link_to gallery.user.username, gallery.user, class: "btn btn-default" %> <%= link_to "#{time_ago_in_words(gallery.created_at)} ago", @gallery %>
    <% end %>
  </div>

app/views/galleries/new.html.erb
<h5>Let's Make a Gallery</h5>

<%= simple_form_for @gallery do |f| %>
  <%= f.input :title %>
  <%= f.button :submit %>

<% end %>

app/views/galleries/show.html.erb
<h3>Should show all the images for this gallery</h3>
<h4> Welcome <%= current_user.username %>!</h4>


<%= link_to "Add Some Pictures", new_photo_path, class: "btn btn-primary" %>

<h3>Photos</h3>
<%= render @gallery.photos %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galleria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>
  <body>

    <nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Galleria</a>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Users", users_path %></li>
      <li><a href="#">About</a></li>
    </ul>
    <div class="navbar-right">
      <% if current_user %>
        <%= link_to "Logout!", logout_path, method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Login!", login_path, class: "btn btn-primary" %>
        <%= link_to "Signup!", new_user_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
  <div class="container">
    <% if flash.any? %>
      <% flash.each do |klass, message| %>
        <div class="alert alert-<%= klass %>" role="alert">
          <p>
            <%= message %>
          </p>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/photos/_photo.html.erb
<%= photo.title %>


<%= image_tag photo.image.versions[:thumbnail].url, class: "img-responsive" if photo.image? %>
<%= button_to "Delete This Picture", photo, method: :delete, class: "btn btn-danger" %>

app/views/photos/index.html.erb
<%= render @photos %>

app/views/photos/new.html.erb
<%= simple_form_for [@gallery, @photo] do |f| %>
  <%= f.input :title %>
  <%= f.input :remote_image_url %>
  <%= f.input :image %>
  <%= f.button :submit %>
<% end%>

app/views/users/index.html.erb
<div class="media">
  <div class="media-left">
    <% @users.each do |user| %>
      <%= simple_format user.username %>
      <strong>Posted by <%= link_to user.username, user.gallery.title, class: "btn btn-default" %> <%= link_to "#{time_ago_in_words(gallery.created_at)} ago" %>
    <% end %>
  </div>

app/views/users/marketing.html.erb
<h4>This page is in memory of the late David from The Iron Yard</h4>
<h5>Title of gallery</h5>
<h6>date created</h6>
<button type="button" class="btn btn-default">Make a New Gallery</button>
<button type="button" class="btn btn-success">Share Gallery</button>
<button type="button" class="btn btn-danger">Delete Gallery</button>
 <%= link_to "Make New Gallery", new_gallery_path(@user), class: "btn btn-default" %>

app/views/users/new.html.erb
<h5>Hello!</h5>

<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit %>

<% end %>

<!-- add the email line after you set up the emailer  -->

app/views/users/show.html.erb
<h4>This page is in memory of the late David from The Iron Yard</h4>
<h5>Title of gallery</h5>
<h6>date created</h6>
<button type="button" class="btn btn-default">Make a New Gallery</button>
<button type="button" class="btn btn-success">Share Gallery</button>
<button type="button" class="btn btn-danger">Delete Gallery</button>
 <%= link_to "Make New Gallery", new_gallery_path(@user), class: "btn btn-default" %>